const CACHE_NAME = 'mega4-pwa-v232';
const PRECACHE_URLS = [
  "./",
  "A2.png",
  "A2_low.webp",
  "K1_btn.png",
  "K2_btn.png",
  "K3_btn.png",
  "K4_btn.png",
  "K5_btn.png",
  "K6_btn.png",
  "K7_btn.png",
  "L13.png",
  "L15.png",
  "L17.png",
  "L18.png",
  "L21.png",
  "L21B.png",
  "L26.png",
  "L27.png",
  "README.txt",
  "apple-touch-icon.png",
  "asset.m4a",
  "asset.png",
  "asset_2.m4a",
  "asset_2.png",
  "asset_3.m4a",
  "asset_3.png",
  "asset_4.m4a",
  "asset_4.png",
  "asset_5.png",
  "audio_01.m4a",
  "audio_02.m4a",
  "balance.png",
  "bg.png",
  "crown_overlay.png",
  "gmt_l.png",
  "gmt_r.png",
  "h24.png",
  "hourHand.png",
  "icon-192.png",
  "icon-512.png",
  "index.html",
  "m_light.html",
  "manifest.webmanifest",
  "minuteHand.png",
  "moon.png",
  "overlay_info.png",
  "pinion1.png",
  "pinion2.png",
  "sec_wheel2.png",
  "tourb_cage.png",
  "turb_unterrad.png"
];
self.addEventListener('install', event => { self.skipWaiting(); event.waitUntil(caches.open(CACHE_NAME).then(cache => cache.addAll(PRECACHE_URLS.map(u => new Request(u, {cache:'reload'}))).catch(()=>{})); });
self.addEventListener('activate', event => { event.waitUntil((async () => { const names = await caches.keys(); await Promise.all(names.map(name => name !== CACHE_NAME ? caches.delete(name) : Promise.resolve())); await self.clients.claim(); })()); });
self.addEventListener('message', event => { if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting(); });
self.addEventListener('fetch', event => { if (event.request.method !== 'GET') return; event.respondWith((async () => { const cached = await caches.match(event.request); if (cached) return cached; try { const res = await fetch(event.request); const cache = await caches.open(CACHE_NAME); cache.put(event.request, res.clone()).catch(()=>{}); return res; } catch(e) { return caches.match('index.html'); } })()); });
